<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>favicon.ico</ApplicationIcon>
    <AssemblyName>NoNoNo</AssemblyName>
    <RootNamespace>NoNoNo</RootNamespace>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>

    <Version>1.0.3</Version>
    <FileVersion>1.0.3.0</FileVersion>
    <AssemblyVersion>1.0.3.0</AssemblyVersion>
    <Authors>Sefa Akbulut</Authors>
    <Company>Sefa Akbulut</Company>
    <Product>NoNoNo Encrypted DNS</Product>
    <Description>Windows Encrypted DNS (DoH) Configuration Tool</Description>
  </PropertyGroup>
</Project>